import { Program } from "@/types";

export const programs: Program[] = [
  {
    id: 1,
    type: "Course",
    title: "Advanced Legal Research ",
    description:
      "Comprehensive course covering modern legal research techniques, database navigation, and case analysis methodologies.",
    date: "2025-02-15",
    time: "10:00 AM",
    duration: "8 weeks",
    location: "Online",
    capacity: 30,
    enrolled: 18,
    price: "$299",
    image:
      "https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 2,
    type: "Workshop",
    title: "Constitutional Law Workshop",
    description:
      "Interactive workshop exploring recent constitutional developments and their practical implications for legal practice.",
    date: "2025-01-28",
    time: "2:00 PM",
    duration: "1 day",
    location: "New Delhi",
    capacity: 50,
    enrolled: 35,
    price: "$149",
    image:
      "https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 3,
    type: "Seminar",
    title: "Digital Rights & Privacy Law",
    description:
      "Expert seminar discussing emerging challenges in digital rights, data protection, and privacy legislation.",
    date: "2025-02-05",
    time: "6:00 PM",
    duration: "3 hours",
    location: "Hybrid",
    capacity: 100,
    enrolled: 100,
    price: "Free",
    image:
      "https://images.pexels.com/photos/5668772/pexels-photo-5668772.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "full",
  },
  {
    id: 4,
    type: "Course",
    title: "Human Rights Advocacy",
    description:
      "Intensive course on human rights law, advocacy strategies, and international legal frameworks.",
    date: "2025-03-01",
    time: "9:00 AM",
    duration: "12 weeks",
    location: "Mumbai",
    capacity: 25,
    enrolled: 12,
    price: "$399",
    image:
      "https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 5,
    type: "Workshop",
    title: "Legal Writing Excellence",
    description:
      "Practical workshop focused on improving legal writing skills, brief preparation, and persuasive argumentation.",
    date: "2025-02-20",
    time: "11:00 AM",
    duration: "2 days",
    location: "Bangalore",
    capacity: 40,
    enrolled: 28,
    price: "$199",
    image:
      "https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 6,
    type: "Seminar",
    title: "Environmental Law Updates",
    description:
      "Current developments in environmental law, climate litigation, and regulatory changes affecting businesses.",
    date: "2025-01-25",
    time: "4:00 PM",
    duration: "2 hours",
    location: "Online",
    capacity: 200,
    enrolled: 156,
    price: "Free",
    image:
      "https://images.pexels.com/photos/5668772/pexels-photo-5668772.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 7,
    type: "Course",
    title: "Human Rights Advocacy",
    description:
      "Intensive course on human rights law, advocacy strategies, and international legal frameworks.",
    date: "2025-03-01",
    time: "9:00 AM",
    duration: "12 weeks",
    location: "Mumbai",
    capacity: 25,
    enrolled: 12,
    price: "$399",
    image:
      "https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 8,
    type: "Workshop",
    title: "Legal Writing Excellence",
    description:
      "Practical workshop focused on improving legal writing skills, brief preparation, and persuasive argumentation.",
    date: "2025-02-20",
    time: "11:00 AM",
    duration: "2 days",
    location: "Bangalore",
    capacity: 40,
    enrolled: 28,
    price: "$199",
    image:
      "https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 9,
    type: "Seminar",
    title: "Environmental Law Updates",
    description:
      "Current developments in environmental law, climate litigation, and regulatory changes affecting businesses.",
    date: "2025-01-25",
    time: "4:00 PM",
    duration: "2 hours",
    location: "Online",
    capacity: 200,
    enrolled: 156,
    price: "Free",
    image:
      "https://images.pexels.com/photos/5668772/pexels-photo-5668772.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 10,
    type: "Workshop",
    title: "Legal Writing Excellence",
    description:
      "Practical workshop focused on improving legal writing skills, brief preparation, and persuasive argumentation.",
    date: "2025-02-20",
    time: "11:00 AM",
    duration: "2 days",
    location: "Bangalore",
    capacity: 40,
    enrolled: 28,
    price: "$199",
    image:
      "https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 11,
    type: "Seminar",
    title: "Environmental Law Updates",
    description:
      "Current developments in environmental law, climate litigation, and regulatory changes affecting businesses.",
    date: "2025-01-25",
    time: "4:00 PM",
    duration: "2 hours",
    location: "Online",
    capacity: 200,
    enrolled: 156,
    price: "Free",
    image:
      "https://images.pexels.com/photos/5668772/pexels-photo-5668772.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 12,
    type: "Course",
    title: "Human Rights Advocacy",
    description:
      "Intensive course on human rights law, advocacy strategies, and international legal frameworks.",
    date: "2025-03-01",
    time: "9:00 AM",
    duration: "12 weeks",
    location: "Mumbai",
    capacity: 25,
    enrolled: 12,
    price: "$399",
    image:
      "https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 13,
    type: "Workshop",
    title: "Legal Writing Excellence",
    description:
      "Practical workshop focused on improving legal writing skills, brief preparation, and persuasive argumentation.",
    date: "2025-02-20",
    time: "11:00 AM",
    duration: "2 days",
    location: "Bangalore",
    capacity: 40,
    enrolled: 28,
    price: "$199",
    image:
      "https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
  {
    id: 14,
    type: "Seminar",
    title: "Environmental Law Updates",
    description:
      "Current developments in environmental law, climate litigation, and regulatory changes affecting businesses.",
    date: "2025-01-25",
    time: "4:00 PM",
    duration: "2 hours",
    location: "Online",
    capacity: 200,
    enrolled: 156,
    price: "Free",
    image:
      "https://images.pexels.com/photos/5668772/pexels-photo-5668772.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop",
    status: "registration-open",
  },
];
